### ISSUE TITLE
Placement games

### ISSUE THREAD

**Issue by ChrisNeedham24** [jamesgiu/quick-hit#6]
Unsure how this would work just yet, would it just auto-generate a competitive game based on ELO?

**Comment by jamesgiu** [comment]
Ohhh like match making?

**Comment by ChrisNeedham24** [comment]
> Ohhh like match making?

Not 100% sure, I don't think I was the one that thought of this. I reckon it could be something like suggesting someone around your ELO that you haven't played for a while?

**Comment by ChrisNeedham24** [comment]
As per Luke: the idea is to have a series of games before you get assigned your initial ELO that would serve to determine your initial ELO. This would create a bigger spread of ELOs as new players would start higher or lower if they go 5-0 or 0-5 in these first placement games.

**Comment by wejrox** [comment]
Most games do placements just by hiding your ELO until you've done 10 games or so. But that's based on the idea that your `mu` is fluctuating at that point and it's discouraging to see big point losses. Not sure what your calculations are but usually that's restricted to an MMR based point system? 
I like the idea of `mu` since it helps stop better players from farming lower rank players?

**Comment by jamesgiu** [comment]
> As per Luke: the idea is to have a series of games before you get assigned your initial ELO that would serve to determine your initial ELO. This would create a bigger spread of ELOs as new players would start higher or lower if they go 5-0 or 0-5 in these first placement games.

Ended up going for this approach but pretty doggedly haha, basically, your ELO has a 5% swing multiplier either way in your first five matches, and your ELO is hidden from all views until you've placed!
